# Generated by Django 3.0.5 on 2020-10-24 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSI_user',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 15, 42, 37, 937197))),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 15, 42, 37, 937197))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 15, 42, 37, 937197))),
                ('company', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSI_web.FSI_user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('num_likes', models.IntegerField()),
                ('num_comments', models.IntegerField()),
                ('num_shares', models.IntegerField()),
                ('content', models.TextField()),
                ('time_create', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSI_web.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('time_create', models.DateTimeField()),
                ('content', models.TextField()),
                ('num_likes', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSI_web.Post')),
            ],
        ),
    ]
